/**
 * ContractViewerApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PowerOfAttorneyDto { 
    id: string;
    contractId: string;
    grantorUserId: string;
    delegateUserId: string;
    validFrom?: string | null;
    validUntil?: string | null;
    createdByUserId?: string | null;
    createdAt?: string;
    revokedAt?: string | null;
    revokedByUserId?: string | null;
    notes?: string;
    referenceNumber?: string | null;
    lastModifiedByUserId?: string | null;
    lastModifiedAt?: string | null;
    isActive?: boolean;
}

